# -*- coding: utf-8 -*-
"""Tugas_akhir_DM.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10UMNGpfQXMV4W_My-w6aUpIovybbAzTV
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

# Membaca dataset dari file CSV
df = pd.read_csv("final.csv")
df

# Memisahkan fitur dan target
X = df[['tempmax', 'tempmin', 'temp', 'feelslikemax', 'feelslikemin', 'dew', 'humidity', 'precip', 'precipprob',
        'precipcover', 'snow', 'snowdepth', 'windspeed', 'winddir', 'sealevelpressure', 'cloudcover', 'visibility',
        'solarradiation', 'solarenergy', 'uvindex', 'cases']]  # Ganti 'cases' dengan nama kolom target yang sesuai

y = df['labels']  # Ganti 'labels' dengan nama kolom target yang sesuai

# Membagi data menjadi data pelatihan dan data uji
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Membuat objek KNN
knn = KNeighborsClassifier(n_neighbors=3)  # Jumlah tetangga yang akan dipertimbangkan (ubah sesuai kebutuhan)

# Melatih model KNN dengan data pelatihan
knn.fit(X_train, y_train)

# Menguji model dengan data uji
y_pred = knn.predict(X_test)

# Menghitung dan menampilkan akurasi
accuracy = accuracy_score(y_test, y_pred)
print("Akurasi model KNN:", accuracy)